### ISSUE TITLE
Update NCSA recommend unbound config

### ISSUE THREAD

**Issue by billglick** [ncsa/puppet-profile_dns_cache#3]
IRST worked with NetEng to update NCSA DNS to address all of the DNS forwarding that we had historically setup in unbound,  allowing the recommended unbound configuration to be greatly simplified.

see:
-  https://jira.ncsa.illinois.edu/browse/SVC-1275?focusedCommentId=444150&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-444150
- https://wiki.ncsa.illinois.edu/display/SecOps/Local+Caching+Resolver

**Comment by billglick** [comment]
I think all of the `profile_dns_cache::reverse_overrides` can now be removed.

**Comment by billglick** [comment]
See https://jira.ncsa.illinois.edu/browse/SVCPLAN-630

**Comment by mollycule** [comment]
Closing as won't fix:

> Benjamin Sperry added a comment - 05/Nov/21 12:01 PM
    Looks to be that unbound by default will return nxdomain when doing a reverse lookup for any private reserved addresses, so looks like the stub-zone and local-zone entries need to stay.

    https://www.claudiokuenzler.com/blog/699/unbound-dns-not-serving-reverse-lookup-for-internal-addresses-rfc1918
